name: CI
on: 
  pull_request:
  push:
    tags:
      - "*"

jobs:
  ci:
    name: Lint, Test and Build on Node ${{ matrix.node }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["18.x", "20.x", "21.x"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Cache turbo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ matrix.node }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-${{ matrix.node }}-

      - name: Install dependencies
        run: npm ci

      - name: Lint, Test and Build
        run: npm run run-all-gha

  typos:
    name: Detect typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run typos
        uses: crate-ci/typos@v1.20.4
