name: CI on PR opened / updated
on: pull_request
jobs:
  ci-on-pr:
    name: Lint & Test on Node ${{ matrix.node }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16.x', '18.x', '19.x', '20.x']

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Cache turbo
        uses: actions/cache@v3
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ matrix.node }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-${{ matrix.node }}-

      - name: Install dependencies
        run: yarn 

      - name: Lint
        run: yarn lint-gha

      - name: Test
        run: yarn test-gha
