name: Check releasability on tags pushed
on:
  push:
    tags:
      - '*'
jobs:
  ci-on-tag:
    name: "Check Releasability (lint, test and build): Node ${{ matrix.node }}"
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16.x', '18.x', '19.x', '20.x']

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Cache turbo
        uses: actions/cache@v3
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ matrix.node }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-${{ matrix.node }}-

      - name: Install dependencies
        uses: yarn

      - name: Lint
        run: yarn lint-gha

      - name: Test
        run: yarn test-gha

      - name: Build
        run: yarn build-gha
